# Blocks
"not_survival:loot" = {}

# Tools

# Not used right now.
# https://minecraft.fandom.com/wiki/Breaking#Speed
"not_survival:tool" = {}

# Food 
"not_survival:food" = {}

# Potion
"not_survival:potion" = {}
