# Blocks
"not_survival:loot" = {}

# Tools

# https://minecraft.fandom.com/wiki/Breaking#Speed
"not_survival:tool" = {}

"not_survival:weapon" = {}

# Food 
"not_survival:food" = {}

# Effect
"not_survival:effect" = {}

# Base fallback
"base:loot" = {}
