# Blocks
"not_survival:loot" = {}

# Tools

# Not used right now.
"not_survival:tool_type" = {}

# https://minecraft.fandom.com/wiki/Breaking#Speed
"not_survival:tool_speed" = {}

# Food. 
"not_survival:food" = {}

# Potion
"not_survival:potion" = {}
